image: node:20-bookworm

stages:
  - install
  - build
  - validation

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules

build:
  stage: build
  script:
    - npm run build

test:
  stage: validation
  needs: ["build"]
  script:
    - npm run test:coverage
  coverage: /All files[^\|]*\|[^\|]*\s+([\d\.]+)/

lint:
  stage: validation
  needs: ["install"]
  script:
    - npm run lint
    - npm run prettier:check

audit:
  stage: validation
  needs: ["install"]
  script:
    - npm audit --omit=dev
