image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run lint
    - npm run prettier:check
    - npm run build
  artifacts:
    paths:
      - node_modules

test:
  stage: test
  script:
    - npm run test:coverage
